### ISSUE TITLE
Bloch sphere plot wrong

### ISSUE THREAD

**Issue by we-taper** [quantastica/quantum-circuit#28] opened 2019-08-28 23:19 UTC
The Bell state prepared by [this circuit](https://quantum-circuit.com/api/embed/html/PzBwz5LpeWtxZjo64) should have a (0,0,0) bloch sphere on each qubits. But the plots of the simulated results shows a pure state on each qubits.

**Comment by perak** [comment] 2019-08-28 23:26
@we-taper thank you for reporting, but I think this is not a bug: state displayed is local state of each qubit. I know it doesn’t show correct state of the system, but entangled state cannot be properly shown graphically in a bloch sphere (at least not in 3 dimensions). I believe 0,0,0 on each qubit is equally correct and equally wrong representation.

**Comment by we-taper** [comment] 2019-08-29 15:47
@peak Thanks for the reply. You are quite right the entangled state cannot be shown faithfully on one qubit Bloch sphere. But I think it might be more useful to show the Bloch sphere of the reduced density matrix on the corresponding one qubit system, like [here](https://algassert.com/quirk#circuit=%7B%22cols%22%3A%5B%5B%22H%22%5D%2C%5B%22%E2%80%A2%22%2C%22X%22%5D%5D%7D) in quirk.

**Comment by perak** [comment] 2019-08-29 17:22
Maybe to implement both: switch on/off between two representations would be the best?

**Comment by perak** [comment] 2020-05-16 21:43
@we-taper almost a year later - it is fixed now.

**Comment by perak** [comment] 2020-05-16 21:45
Also, bloch spheres are shown directly in the circuit editor (and auto-updates as gates are added/removed).

<img width="739" alt="Screen Shot 2020-05-16 at 11 44 02 PM" src="https://user-images.githubusercontent.com/5630814/82130841-4206fc80-97cf-11ea-9ae6-3a95da99a359.png">

**Comment by we-taper** [comment] 2020-05-17 16:38
Wonderful!

**Closed** 2020-05-17 16:39 UTC
